sudo: required

services: docker

before_install:
	- docker-compose up -d --build

script:
	# - docker-compose exec django python manage.py migrate --noinput
	# - docker-compose exec django python manage.py test
	- python manage.py test
